# Generated by Django 3.0.5 on 2020-08-27 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0002_galleryphotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphotos',
            name='parcours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accueil.Accueil', verbose_name='Le parcours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galleryphotos',
            name='title',
            field=models.CharField(default='', max_length=254),
        ),
    ]
